[workspace]
members = [
    "core/*",
    "utils/*",
    "cli",
    "trader",
    "node",
    "postgres-worker",
    "trading-view-api",
]
resolver = "2"

[profile.release]
overflow-checks = true
strip = true
