[workspace]
members = [
    "core/*",
    "utils/*",
    "cli",
    "trader",
    "node",
    "gateway",
    "indexer",
    #"wasm_swapper",
]
resolver = "2"

[profile.release]
overflow-checks = true
strip = true

[workspace.dependencies]
tokio = { version = "1.34.0", features = ["full"] }
anyhow = "1.0.79"
alloy = { version = "0.8.3", features = ["full", "serde"] }
