version: '3.9'

services:
  postgres:
    container_name: postgres
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
        - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=pass
      - POSTGRES_USER=user
      - POSTGRES_DB=main_db
    restart: on-failure
    networks:
      - database
  clickhouse:
    container_name: clickhouse
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8002:9000"
      - "9123:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    environment:
      - CLICKHOUSE_DB=trades
      - CLICKHOUSE_USER=trader
      - CLICKHOUSE_PASSWORD=trader
    restart: on-failure
    networks:
      - database
  indexer:
    build:
      context: .
      args:
        BIN: multipool-indexer
    environment:
      DATABASE_URL: postgresql://user:pass@postgres:5432/main_db
      HTTP_URL: https://arb-sepolia.g.alchemy.com/v2/c_34X8mrHf2CeUbKJyRn9El7loLauTbU
      WS_URL: wss://arb-sepolia.g.alchemy.com/v2/c_34X8mrHf2CeUbKJyRn9El7loLauTbU
      KAFKA_URL: http://0.0.0.0:9092
      KAFKA_TOPIC: chain_events
    depends_on:
      - postgres
      - kafka
    restart: always
    networks:
      - database
  trader:
    build: 
      context: .
      args:
        BIN: trader
    environment:
      DATABASE_URL: postgresql://user:pass@postgres:5432/main_db
      PRIVATE_KEY_FILE: /run/secrets/pk
      HTTP_URL: https://arb-sepolia.g.alchemy.com/v2/c_34X8mrHf2CeUbKJyRn9El7loLauTbU
      CLICKHOUSE_DB: trades
      CLICKHOUSE_URL: clickhouse
      CLICKHOUSE_USER: trader
      CLICKHOUSE_PASSWORD: trader
      KAFKA_GROUP: trader
      KAFKA_URL: https://localhost:9092
      KAFKA_TOPIC: chain_events
    depends_on:
      - postgres
      - kafka
    restart: on-failure
    networks:
      - database
    secrets:
      - pk
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - '2181:2181'
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_LISTENERS: CONTROLLER://localhost:9091,HOST://0.0.0.0:9092,DOCKER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: HOST://localhost:9092,DOCKER://kafka:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER:PLAINTEXT,HOST:PLAINTEXT

      # Settings required for KRaft mode
      KAFKA_NODE_ID: 1
      CLUSTER_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@localhost:9091
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER
    networks:
      - database
volumes:
  db: {}
  clickhouse: {}
secrets:
   pk: 
    file: pk.txt

networks:
  database:
    # Specify driver options
    driver: bridge