[package]
name = "gateway"
version = "0.1.0"
edition = "2021"

[dependencies]
log.workspace = true

axum.workspace = true
anyhow.workspace = true
tokio.workspace = true
sqlx.workspace = true
alloy.workspace = true

dashmap.workspace = true
serde.workspace = true
serde_json.workspace = true
