[package]
name = "trading-view-api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio={ version = "1.34.0", features = ["full"] }
postgres="0.19.7"
tokio-postgres = "0.7.10"
actix-web = "4"
log = "0.4.20"
serde = { version = "1.0.192", features = ["derive"] }
serde_json="1.0.108"
