[package]
name = "indexer"
version = "0.1.0"
edition = "2021"

[dependencies]
multipool-storage = { version = "0.1.0", path = "../core/storage" }

tokio.workspace = true
anyhow.workspace = true
alloy.workspace = true
futures = "0.3.31"
