service_name: "indexer"
health_check: "0.0.0.0:3030"
environment: "dev"
config:
  rpc_url: https://arb-sepolia.g.alchemy.com/v2/c_34X8mrHf2CeUbKJyRn9El7loLauTbU
  kafka_url: kafka:9092
  from_block: 137751082
  chain_id: 421614
  # database_url: postgresql://user:pass@postgres:5432/main_db
  database_url: postgresql://googrand:googrand@localhost:5432/indexer
  