service_name: "trader"
health_check: "0.0.0.0:3030"
environment: "dev"
config:
  clickhouse:
    url: localhost:9000
    user: googrand
    password: googrand
    database: trades
  rpc_url: 'https://monad-testnet.g.alchemy.com/v2/c_34X8mrHf2CeUbKJyRn9El7loLauTbU'
  pk_file: ./trader_pk.txt
  