name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build-tv-bot:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the indexer image
      run: docker build tv-bot --tag badconfig/tv-bot

    - name: Login to dockerhub
      run: docker login -u="${{ vars.DOCKER_USERNAME }}" -p="${{ secrets.DOCKER_PASSWORD }}"

    - name: push image
      run: docker push badconfig/tv-bot

  build-backend-api:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build api --tag badconfig/backend-api

    - name: Login to dockerhub
      run: docker login -u="${{ vars.DOCKER_USERNAME }}" -p="${{ secrets.DOCKER_PASSWORD }}"

    - name: push image
      run: docker push badconfig/backend-api 

  build-price-oracle:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build price-oracle --tag badconfig/price-oracle

    - name: Login to dockerhub
      run: docker login -u="${{ vars.DOCKER_USERNAME }}" -p="${{ secrets.DOCKER_PASSWORD }}"

    - name: push image
      run: docker push badconfig/price-oracle 

  build-target-share-oracle:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build target-share-oracle --tag badconfig/target-share-oracle

    - name: Login to dockerhub
      run: docker login -u="${{ vars.DOCKER_USERNAME }}" -p="${{ secrets.DOCKER_PASSWORD }}"

    - name: push image
      run: docker push badconfig/target-share-oracle 
