name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-multipool-tracker:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build price-oracle image
      run: docker build multipool-tracker --target price-oracle --tag badconfig/arcanum-price-oracle

    - name: Build trader image
      run: docker build multipool-tracker --target trader --tag badconfig/arcanum-trader

    - name: Login to dockerhub
      run: docker login -u="${{ vars.DOCKER_USERNAME }}" -p="${{ secrets.DOCKER_PASSWORD }}"

    - name: push price-oracle image
      run: docker push badconfig/arcanum-price-oracle

    - name: push trader image
      run: docker push badconfig/arcanum-trader

  build-backend-api:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build the Docker image
      run: docker build api --tag badconfig/backend-api

    - name: Login to dockerhub
      run: docker login -u="${{ vars.DOCKER_USERNAME }}" -p="${{ secrets.DOCKER_PASSWORD }}"

    - name: push image
      run: docker push badconfig/backend-api 
